In [55]:
import pandas as pd

In [56]:
#creating lists
x={
    "R.No" : [1,2,3,4,5],
    "Mark" : [100,99,98,97,94]
}

In [57]:
#creating lists
y={
    "R.No" : [1,2,3,4,5],
    "Name" : ["Sathish","Karan","Sivant","Thiru","Akhil"]
}

In [58]:
#creating lists
z={
    "R.No" : [1,2,3,4,5],
    "Conduct" :["Excelent","Outstanding","Super","Good","Fantastic"]
}

In [59]:
#creating x dataframe
xdf= pd.DataFrame(x)
xdf


R.No  Mark
0     1   100
1     2    99
2     3    98
3     4    97
4     5    94

In [60]:
#creating y dataframe
ydf = pd.DataFrame(y)
ydf

R.No     Name
0     1  Sathish
1     2    Karan
2     3   Sivant
3     4    Thiru
4     5    Akhil

In [61]:
#creating z dataframe
zdf= pd.DataFrame(z)
zdf

R.No      Conduct
0     1     Excelent
1     2  Outstanding
2     3        Super
3     4         Good
4     5    Fantastic

In [62]:
#creating excel file with multiple sheets
with pd.ExcelWriter("data.xlsx") as excel:
    xdf.to_excel(excel,sheet_name="Mark list")
    ydf.to_excel(excel,sheet_name="Name list")
    zdf.to_excel(excel,sheet_name="Ranking")

In [63]:
#importing data in specified sheet
xr = pd.read_excel("data.xlsx",sheet_name="Mark list")
xrf = pd.DataFrame(xr)


In [64]:
#short summary
xrf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
Unnamed: 0    5 non-null int64
R.No          5 non-null int64
Mark          5 non-null int64
dtypes: int64(3)
memory usage: 200.0 bytes


In [65]:
#providing some basic info
xrf.describe()

Unnamed: 0      R.No        Mark
count    5.000000  5.000000    5.000000
mean     2.000000  3.000000   97.600000
std      1.581139  1.581139    2.302173
min      0.000000  1.000000   94.000000
25%      1.000000  2.000000   97.000000
50%      2.000000  3.000000   98.000000
75%      3.000000  4.000000   99.000000
max      4.000000  5.000000  100.000000

In [66]:
#importing data in specified sheet
yr = pd.read_excel("data.xlsx","Name list")
yrf = pd.DataFrame(yr)



In [67]:
#short summary
yrf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
Unnamed: 0    5 non-null int64
R.No          5 non-null int64
Name          5 non-null object
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [68]:
#providing some basic info
yrf.describe()

Unnamed: 0      R.No
count    5.000000  5.000000
mean     2.000000  3.000000
std      1.581139  1.581139
min      0.000000  1.000000
25%      1.000000  2.000000
50%      2.000000  3.000000
75%      3.000000  4.000000
max      4.000000  5.000000

In [69]:
#importing data in specified sheet
zr = pd.read_excel("data.xlsx","Ranking")
zrf = pd.DataFrame(zr)


In [70]:
#short summary
zrf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
Unnamed: 0    5 non-null int64
R.No          5 non-null int64
Conduct       5 non-null object
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [71]:
#providing some basic info
zrf.describe()

Unnamed: 0      R.No
count    5.000000  5.000000
mean     2.000000  3.000000
std      1.581139  1.581139
min      0.000000  1.000000
25%      1.000000  2.000000
50%      2.000000  3.000000
75%      3.000000  4.000000
max      4.000000  5.000000

In [72]:
#importing load_digits datasets
from sklearn.datasets import load_digits
from sklearn import preprocessing

In [73]:
#assinging to a variable
digits =load_digits()


In [74]:
#display shape of our dataset
print (digits.data.shape)

(1797, 64)


In [75]:
x= digits.data
y= digits.target

In [76]:
#normilizing data
normalized_x=preprocessing.normalize(x)
y=y.reshape(1,-1)
#normalizing target
normalized_y=preprocessing.normalize(y)


In [77]:
normalized_x

array([[0.        , 0.        , 0.09024036, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.15413829, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.24153867, 0.1358655 ,
        0.        ],
       ...,
       [0.        , 0.        , 0.0140138 , ..., 0.08408278, 0.        ,
        0.        ],
       [0.        , 0.        , 0.03044313, ..., 0.18265877, 0.        ,
        0.        ],
       [0.        , 0.        , 0.14230641, ..., 0.17076769, 0.01423064,
        0.        ]])

In [78]:
normalized_y

array([[0.        , 0.00442868, 0.00885736, ..., 0.03542946, 0.03985814,
        0.03542946]])

In [79]:
#standardizing data
scaled_x=preprocessing.scale(normalized_x)
scaled_x

array([[ 0.        , -0.33655106,  0.07819821, ..., -1.14176167,
        -0.50519622, -0.1961923 ],
       [ 0.        , -0.33655106, -1.10039696, ...,  0.46599183,
        -0.50519622, -0.1961923 ],
       [ 0.        , -0.33655106, -1.10039696, ...,  1.37762949,
         1.55008272, -0.1961923 ],
       ...,
       [ 0.        , -0.33655106, -0.91736807, ..., -0.26472858,
        -0.50519622, -0.1961923 ],
       [ 0.        , -0.33655106, -0.70279078, ...,  0.7634773 ,
        -0.50519622, -0.1961923 ],
       [ 0.        , -0.33655106,  0.75821316, ...,  0.6394463 ,
        -0.28992497, -0.1961923 ]])

In [80]:
#standardizing target
scaled_y=preprocessing.scale(normalized_y)
scaled_y

array([[0., 0., 0., ..., 0., 0., 0.]])

In [81]:
#importing load_breast_cancer datasets
from sklearn.datasets import load_breast_cancer
from sklearn import preprocessing


In [82]:
#loading data in a variable
cancer =load_breast_cancer()

In [83]:
#displaying shape
print (cancer.data.shape)

(569, 30)


In [84]:
x= cancer.data
y= cancer.target

In [85]:
#normalizing data
normalized_x=preprocessing.normalize(x)
y=y.reshape(1,-1)
#normalizing target
normalized_y=preprocessing.normalize(y)

In [86]:
normalized_x

array([[7.92541486e-03, 4.57286305e-03, 5.40989964e-02, ...,
        1.16920795e-04, 2.02695018e-04, 5.23808686e-05],
       [8.66575595e-03, 7.48616836e-03, 5.59882822e-02, ...,
        7.83583182e-05, 1.15852352e-04, 3.75024596e-05],
       [9.36668268e-03, 1.01087865e-02, 6.18419883e-02, ...,
        1.15596947e-04, 1.71873157e-04, 4.16624718e-05],
       ...,
       [1.16438847e-02, 1.96964025e-02, 7.59658259e-02, ...,
        9.94640269e-05, 1.55579134e-04, 5.48525170e-05],
       [9.23020523e-03, 1.31418408e-02, 6.27743569e-02, ...,
        1.18738077e-04, 1.83125480e-04, 5.55604587e-05],
       [2.31098880e-02, 7.30820427e-02, 1.42709515e-01, ...,
        0.00000000e+00, 8.55006294e-04, 2.09626935e-04]])

In [87]:
normalized_y

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.05292561,
        0.05292561, 0.05292561, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.05292561, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.05292561, 0.        , 0.05292561, 0.05292561,
        0.05292561, 0.05292561, 0.05292561, 0.        , 0.        ,
        0.05292561, 0.        , 0.        , 0.05292561, 0.05292561,
        0.05292561, 0.05292561, 0.        , 0.05292561, 0.        ,
        0.        , 0.05292561, 0.05292561, 0.05292561, 0.05292561,
        0.        , 0.05292561, 0.        , 0.  

In [88]:
#standardizing data
scaled_x=preprocessing.scale(normalized_x)
scaled_x

array([[-1.72631363, -1.57560034, -1.68366795, ...,  0.16324156,
        -0.78073382, -0.83405814],
       [-1.54156292, -1.3123605 , -1.60776296, ..., -0.5673826 ,
        -1.29284946, -1.10134931],
       [-1.36664799, -1.07538651, -1.37258122, ...,  0.13815927,
        -0.96249192, -1.02661454],
       ...,
       [-0.79837657, -0.20907068, -0.80513409, ..., -0.16750319,
        -1.0585786 , -0.78965489],
       [-1.40070568, -0.80132642, -1.33512186, ...,  0.1976727 ,
        -0.89613639, -0.77693669],
       [ 2.06294269,  4.61473797,  1.87639731, ..., -2.05199887,
         3.06597911,  1.9908732 ]])

In [89]:
#standardizing target
normalized_y=normalized_y.reshape(1,-1)
scaled_y=preprocessing.scale(normalized_y)
scaled_y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 