## Visualising accurracy

# <font color = "brown" size = 6>Training model:
    1.Import packages
     
    2.read csv file
    
    3.identify x and y axis variables
    
    4.split the test and train data(random_state = to lock values)
    
    5.create the object for linear regression
    
    6.train the model using fit function
    
    7.calculate the intersect line y = mx+b
    
    8.calculate the coef value to note the changes
    
    9.test the x_test value by using predict function and Store it
    
    10.draw and display the actual and predicted values
     
    11.calculate the error rate
                    * Mean Absolute error
                    * Mean squared error
                    * Root mean squared error

In [1]:
#confusion matrix to visualize matrices
from sklearn.metrics import confusion_matrix
#accuracy_score to visualize accuracy of our model
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

In [2]:
#original output
import numpy as np
actual = np.array([1.,0,0.0,1,0,0,1,0])
#predicted output
predicted = np.array([1,0,1.0,1,1.0,0,0,0])
print(type(actual), actual.shape, type(predicted))

<class 'numpy.ndarray'> (8,) <class 'numpy.ndarray'>


In [3]:
#fitting our actal and prediction to confusion matrix model
results= confusion_matrix(actual,predicted)
print("Confusion Matrix : ")
print(results)

#printing accuracy scores
print("Accuracy score : ",accuracy_score(actual,predicted))

Confusion Matrix : 
[[3 2]
 [1 2]]
Accuracy score :  0.625


In [4]:
import pandas as pd

In [5]:
actual1 = [6,0,9,1,12,6,1,3,12,56,78,23]
#predicted output
predicted1= [6,9,3,4,0,6,2,3,23,45,78,89]

In [6]:
#fitting our actal and prediction to confusion matrix model
results= confusion_matrix(actual1,predicted1)
print("Confusion Matrix : ")
print(results)
#printing accuracy scores
print("Accuracy score : ",accuracy_score(actual1,predicted1))

Confusion Matrix : 
[[0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
Accuracy score :  0.3333333333333333


## Classification Metrics

In [7]:
#classification metrics to visualize data
from sklearn.metrics import classification_report

In [8]:
print(classification_report(actual1,predicted1))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         0
           3       0.50      1.00      0.67         1
           4       0.00      0.00      0.00         0
           6       1.00      1.00      1.00         2
           9       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         0
          56       0.00      0.00      0.00         1
          78       1.00      1.00      1.00         1
          89       0.00      0.00      0.00         0

   micro avg       0.33      0.33      0.33        12
   macro avg       0.19      0.23      0.21        12
weighted avg       0.29      0.33      0.31        12



C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


## Linear Regression
## One category

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pyp
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn import metrics
%matplotlib inline

In [10]:
#for locking test and train separatiion.similar to "Seed"
random_state = 0

In [11]:
data = pd.read_csv("Weather_new.csv")

C:\Users\SATHISH\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (7,8,18,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [12]:
data.head()

STA      Date Precip  WindGustSpd    MaxTemp    MinTemp   MeanTemp  \
0  10001  1942-7-1  1.016          NaN  25.555556  22.222222  23.888889   
1  10001  1942-7-2      0          NaN  28.888889  21.666667  25.555556   
2  10001  1942-7-3   2.54          NaN  26.111111  22.222222  24.444444   
3  10001  1942-7-4   2.54          NaN  26.666667  22.222222  24.444444   
4  10001  1942-7-5      0          NaN  26.666667  21.666667  24.444444   

  Snowfall PoorWeather  YR  ...  FB  FTI ITH  PGT  TSHDSBRSGF  SD3  RHX  RHN  \
0        0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
1        0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
2        0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
3        0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   
4        0         NaN  42  ... NaN  NaN NaN  NaN         NaN  NaN  NaN  NaN   

  RVG  WTE  
0 NaN  NaN  
1 NaN  NaN  
2 NaN  NaN  
3 NaN  NaN  
4 NaN  NaN  

[5 rows x 31 columns]

In [13]:
data.shape

(119040, 31)

In [14]:
data.describe()

STA  WindGustSpd        MaxTemp        MinTemp  \
count  119040.000000   532.000000  119040.000000  119040.000000   
mean    29659.435795    37.774534      27.045111      17.789511   
std     20953.209402    10.297808       8.717817       8.334572   
min     10001.000000    18.520000     -33.333333     -38.333333   
25%     11801.000000    29.632000      25.555556      15.000000   
50%     22508.000000    37.040000      29.444444      21.111111   
75%     33501.000000    43.059000      31.666667      23.333333   
max     82506.000000    75.932000      50.000000      34.444444   

            MeanTemp             YR             MO             DA          DR  \
count  119040.000000  119040.000000  119040.000000  119040.000000  533.000000   
mean       22.411631      43.805284       6.726016      15.797530   26.998124   
std         8.297982       1.136718       3.425561       8.794541   15.221732   
min       -35.555556      40.000000       1.000000       1.000000    2.000000   
25%        20.555556      43.000000       4.000000       8.000000   11.000000   
50%        25.555556      44.000000       7.000000      16.000000   32.000000   
75%        27.222222      45.000000      10.000000      23.000000   34.000000   
max        40.000000      45.000000      12.000000      31.000000   78.000000   

              SPD  ...   FT   FB  FTI  ITH         PGT  SD3  RHX  RHN  RVG  \
count  532.000000  ...  0.0  0.0  0.0  0.0  525.000000  0.0  0.0  0.0  0.0   
mean    20.396617  ...  NaN  NaN  NaN  NaN   12.085333  NaN  NaN  NaN  NaN   
std      5.560371  ...  NaN  NaN  NaN  NaN    5.731328  NaN  NaN  NaN  NaN   
min     10.000000  ...  NaN  NaN  NaN  NaN    0.000000  NaN  NaN  NaN  NaN   
25%     16.000000  ...  NaN  NaN  NaN  NaN    8.500000  NaN  NaN  NaN  NaN   
50%     20.000000  ...  NaN  NaN  NaN  NaN   11.600000  NaN  NaN  NaN  NaN   
75%     23.250000  ...  NaN  NaN  NaN  NaN   15.000000  NaN  NaN  NaN  NaN   
max     41.000000  ...  NaN  NaN  NaN  NaN   23.900000  NaN  NaN  NaN  NaN   

       WTE  
count  0.0  
mean   NaN  
std    NaN  
min    NaN  
25%    NaN  
50%    NaN  
75%    NaN  
max    NaN  

[8 rows x 24 columns]

In [15]:
X = data['MinTemp'].values.reshape(-1,1)
y = data['MaxTemp'].values.reshape(-1,1)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [17]:
regressor = LinearRegression()  
regressor.fit(X_train, y_train) #training the algorithm


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [18]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

[10.66185201]
[[0.92033997]]


In [19]:
y_pred = regressor.predict(X_test)

In [20]:
#comparing Actual and Predicted
df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df

Actual  Predicted
0      28.888889  33.670351
1      31.111111  30.091251
2      27.222222  26.512151
3      28.888889  31.113851
4      23.333333  15.774852
5      37.222222  30.602551
6      22.222222  11.684452
7      35.555556  33.670351
8      30.555556  30.602551
9      28.888889  32.647751
10     24.444444  29.068651
11     22.777778  23.955652
12     30.555556  30.091251
13     26.111111  26.000851
14     27.222222  29.068651
15     30.555556  32.647751
16     10.555556  15.774852
17     32.222222  32.136451
18     29.444444  29.579951
19     23.333333  18.842652
20     30.555556  26.000851
21     43.333333  31.113851
22     27.222222  30.091251
23     33.333333  33.159051
24     31.111111  22.421752
25     30.000000  31.113851
26     33.333333  30.602551
27     31.111111  30.602551
28     33.333333  35.204251
29     36.111111  30.091251
...          ...        ...
23778   4.444444   9.639252
23779  31.111111  32.136451
23780  30.000000  32.136451
23781  34.444444  30.091251
23782  28.888889  32.647751
23783  32.222222  29.068651
23784  25.000000  15.774852
23785  26.666667  30.091251
23786  35.000000  32.136451
23787  15.000000  12.195752
23788  19.444444  22.421752
23789  15.000000  19.865252
23790  33.333333  25.489551
23791  27.777778  26.000851
23792  31.666667  30.091251
23793  31.666667  31.625151
23794  29.444444  31.113851
23795  29.444444  33.670351
23796  16.666667  17.820052
23797  20.000000  21.399152
23798  28.888889  32.136451
23799  31.111111  30.091251
23800  44.444444  35.715551
23801  36.666667  36.226851
23802  29.444444  33.159051
23803  32.777778  32.136451
23804  32.222222  29.068651
23805  31.111111  32.647751
23806  31.111111  30.602551
23807  36.666667  31.625151

[23808 rows x 2 columns]

In [21]:
#Predicting errors
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


Mean Absolute Error: 3.19932917837853
Mean Squared Error: 17.631568097568447
Root Mean Squared Error: 4.198996082109204


In [22]:
#accuracy score of our model
print("Accuracy score : ",accuracy_score(y_test.round(), y_pred.round()))

Accuracy score :  0.10345262096774194


In [23]:
#np.ravel(y_train,0)
y_train.reshape(-1)

array([27.22222222, 32.77777778,  8.88888889, ...,  4.44444444,
       14.44444444, 21.11111111])

In [24]:
#encoding values for logistic regression
lab_enc = preprocessing.LabelEncoder()
encoded = lab_enc.fit_transform(X_train)
encoded1 = lab_enc.fit_transform(y_train)


C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
#calling an instance of model
logregression = LogisticRegression()
logregression.fit(encoded.reshape(-1,1),encoded1)

C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
#predicting y value
y_pred = logregression.predict(X_test)

In [27]:
#accuracy of same dataset withlogistic regression decreases
accuracy_score(y_test.round(), y_pred.round())

0.030031922043010754

## Multipe categories

In [28]:
#importing our data
dataset = pd.read_csv("winequality.csv")

In [29]:
dataset.shape


(1599, 12)

In [30]:
#decribe about mean,sts etc.
dataset.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [31]:
#checking whether any column is null
dataset.isnull().any()


fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [32]:
#if any is null filling it with ffill method(ffill = forwardfill(copies next value to blank cells))
dataset = dataset.fillna(method='ffill')


In [33]:
#dividinf labels
X = dataset[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates','alcohol']].values
y = dataset['quality'].values


In [34]:
#splitting our data(test = 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [35]:
#FIITING OUR MODEL
regressor = LinearRegression()  
regressor.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [36]:
#CHECKING REGRESSOR AND COEFFICIENT
x = pd.DataFrame(X)
coeff_df = pd.DataFrame(regressor.coef_, x.columns,columns = [ "coeffieient"])
coeff_df

coeffieient
0      0.041284
1     -1.149528
2     -0.177927
3      0.027870
4     -1.873407
5      0.002684
6     -0.002777
7    -31.516666
8     -0.254486
9      0.924040
10     0.267797

In [37]:
#predicting y values
y_pred = regressor.predict(X_test)

In [38]:
#comparing actual and predicted
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

Actual  Predicted
0         6   5.782930
1         5   5.036193
2         7   6.596989
3         6   5.339126
4         5   5.939529
5         6   5.007207
6         5   5.396162
7         6   6.052112
8         4   4.867603
9         5   4.950676
10        5   5.285804
11        5   5.412653
12        6   5.705742
13        5   5.129217
14        6   5.528852
15        6   6.380524
16        7   6.810125
17        5   5.738033
18        5   5.976188
19        4   5.086134
20        7   6.344799
21        6   5.164010
22        6   5.642040
23        4   6.146290
24        6   5.481780
25        5   5.033914
26        5   5.187213
27        7   6.487837
28        5   5.333014
29        6   6.304583
..      ...        ...
290       5   5.681639
291       6   5.420867
292       6   6.125389
293       6   5.314067
294       5   5.195282
295       6   5.701786
296       6   5.567547
297       5   5.146705
298       6   5.155564
299       5   5.240076
300       6   5.698923
301       5   5.063826
302       6   5.358932
303       6   5.696057
304       6   6.103812
305       6   5.849924
306       5   5.337224
307       5   5.051586
308       6   5.592078
309       5   5.308725
310       5   5.910322
311       6   5.923909
312       5   5.349487
313       5   5.356317
314       5   5.101599
315       6   6.559757
316       4   6.017576
317       5   6.251291
318       4   5.163926
319       6   6.367205

[320 rows x 2 columns]

In [39]:
#finding our errors of our model
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


Mean Absolute Error: 0.46963309286611066
Mean Squared Error: 0.3844711978201244
Root Mean Squared Error: 0.6200574149384268


In [40]:
#Accuracy score of linear regression model
print("Accuracy score in Linear Reegression : ",accuracy_score(y_pred.round(),y_test))

Accuracy score in Linear Reegression :  0.63125


In [41]:
#fitting logistic regression model
logregressor = LogisticRegression()
logregressor.fit(X_train,y_train)

C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\SATHISH\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [42]:
#predicting for logistic regression
y_pred = logregressor.predict(X_test)

In [43]:
#accuracy score hereaslo reduces for logistic regression model
print("Accuracy Score in Logistic Regression - ",accuracy_score(y_pred,y_test))

Accuracy Score in Logistic Regression -  0.628125
