# Creating Numpy Array


In [1]:
#importing numpy package
import numpy as np

In [2]:
#creating a list
my_list=[1,2,3,4]

In [3]:
array_my_list = np.array(my_list)

In [4]:
array_my_list.reshape(1,-1)

array([[1, 2, 3, 4]])

In [5]:
#creating a nested list
my_nes_list = [[1,2,3],[4,5,6],[7,8,9]]
len(my_nes_list)

3

In [6]:
array_my_nes_list = np.array(my_nes_list)

In [7]:
array_my_nes_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#creting numbers within a range(start,stop,step)
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
#creating 0 matrix
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#creating a matrix with values of 1
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
#creating a list with definite intervels(start,stop,required numbers of values)
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [13]:
#creating a identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#random numbers between 0 and 1
np.random.rand(4,5)

array([[0.47374918, 0.68765119, 0.60987966, 0.74496683, 0.44472078],
       [0.42581867, 0.91212957, 0.10732731, 0.81571576, 0.54305252],
       [0.3173716 , 0.62347529, 0.67034846, 0.01340878, 0.1057461 ],
       [0.44291146, 0.16003762, 0.75466036, 0.65195445, 0.09891107]])

In [15]:
#random numbers with standard normal distribution(mean = 0 ,std = 1)
np.random.randn(4)

array([-1.19191545,  1.83375722,  1.10202757, -0.14282234])

In [16]:
import random
random.seed(2)
np.random.randint(-100,100)

-9

In [17]:
#random whole integers
arr = np.random.randint(0,100,25)

In [18]:

arr

array([19,  8, 99, 45, 20, 60, 27, 15,  6, 95, 33, 13, 64, 48, 40, 70,  6,
       96, 50, 28, 37, 83, 99, 41,  3])

In [19]:
#reshaping arrays
a = arr.reshape(5,5)

In [20]:
#max value in a array
arr.max()

99

In [21]:
#min value in a array
arr.min()

3

In [22]:
#defining position of max value
arr.argmax()

2

In [23]:
#defining position of min value
a.argmin(axis=0)

array([0, 3, 1, 1, 4], dtype=int64)

In [24]:
#1d array shape(vector)
arr.shape

(25,)

In [25]:
#determing shape of a matrix
a.shape

(5, 5)

In [26]:
arra = np.arange(1,11)

In [27]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Numpy Indexing and Selections


## 1_d arrays


In [28]:
#array indexing
arra[8]

9

In [29]:
#array indexing with limits
arra[4:6]

array([5, 6])

In [30]:
#from staring till 5 th index
arra[ :6]

array([1, 2, 3, 4, 5, 6])

In [31]:
#from 1 til end index

arra[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
#displaying full array
arra[ : ]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
#reversing array
arra[ : :-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [34]:
#changing values with range specified
arra[1:3] = 100

In [35]:
arra

array([  1, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [36]:
#creating a new sliced array
slice_arra = arra[0:6]

In [37]:
#changing all values of sliced array to 97
slice_arra[:] =97

In [38]:
slice_arra

array([97, 97, 97, 97, 97, 97])

In [39]:
#copying whole numpy array
copy_arra = arra.copy()

In [40]:
copy_arra

array([97, 97, 97, 97, 97, 97,  7,  8,  9, 10])

## 2_d arrays


In [41]:
#creating random arrays
arra_2d = np.random.randint(0,100,size=(10, 4))

In [42]:
arra_2d

array([[49, 59,  8, 16],
       [37, 59, 36, 92],
       [81, 92, 22, 87],
       [58, 66, 41, 65],
       [45, 46, 72, 30],
       [88, 41, 84, 77],
       [30, 13, 11,  9],
       [94, 47, 79, 24],
       [23, 12, 80, 91],
       [69, 50, 51, 13]])

In [43]:
#accessing specified row and column
arra_2d[1][3] 

92

In [44]:
#diiferent way to access row and column
arra_2d[1,3]

92

In [45]:
#slicinf with parameters( row start:row end,column start:coumn end)
arra_2d[:2,0:]

array([[49, 59,  8, 16],
       [37, 59, 36, 92]])

In [46]:
#to check values greater than 50
bool_arra = arra>50

In [47]:
#accessing boolean outputs
bool_arra


array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [48]:
#accessing values 
arra[bool_arra]

array([97, 97, 97, 97, 97, 97])

In [49]:
#another way to access values greater than 50
arra[arra>50]

array([97, 97, 97, 97, 97, 97])

In [50]:
arra[arra<50]

array([ 7,  8,  9, 10])

In [51]:
#creating 2d arrays with arange
arr_2d = np.arange(100).reshape(25,4)

In [52]:
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

# Numpy Operations


## 1 .Array with arrays
## 2 . Array with scalars
## 3 . Universal array functions


In [53]:
#initializing arrays
array1 = np.array([10,20,30,40,50])
array2 = np.arange(5)
array2


array([0, 1, 2, 3, 4])

In [54]:
#adding arrays
array_tot = array1 + array2

In [55]:
array_tot

array([10, 21, 32, 43, 54])

In [56]:
#subtracting arrays
array_sub = array1-array2

In [57]:
#exponential of array1
np.exp(array1)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [58]:
#log value of array2
np.log(array2)

C:\Users\SATHISH\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [59]:
#sum of a specific array
array2.sum()

10

In [60]:
#min of a specific array
array2.min()

0

# GROUPBY 


In [61]:
import pandas as pd
df = pd.read_csv("weather.csv")


In [62]:
df.head(45)

Day  Temperature   Wind Speed           Event
0   01/01/2018            35         320           Rainy
1   02/01/2018            28         123           cloud
2   03/01/2018            26         156             Hot
3   04/01/2018            29         174  not available 
4   05/01/2018            30         185           Rainy
5   06/01/2018            31         169           cloud
6   07/01/2018            32         245             Hot
7   08/01/2018            35         123  not available 
8   09/01/2018            40         156           cloud
9   10/01/2018            22         147             Hot
10  11/01/2018            35         563  not available 
11  12/01/2018            28         156           cloud
12  13/01/2018            24         412             Hot
13  14/01/2018            26         457           Rainy
14  01/02/2018            32         423           cloud
15  02/02/2018            35         156             Hot
16  03/02/2018            36         148  not available 
17  04/02/2018            37         175  not available 
18  05/02/2018            35         245           Rainy
19  06/02/2018            22         265             Hot
20  07/02/2018            25         245             Hot
21  08/02/2018            29         231  not available 
22  09/02/2018            30         269             Hot
23  10/02/2018            32         269           Rainy
24  11/02/2018            32         247           Rainy
25  01/03/2018            31         258           Rainy
26  02/03/2018            41         265           Rainy
27  03/03/2018            42         236             Hot
28  04/03/2018            43         254             Hot
29  05/03/2018            25         258           cloud
30  06/03/2018            28         236  not available 
31  07/03/2018            21         254             NaN
32  08/03/2018            20         245           Rainy
33  09/03/2018            35         285           cloud
34  10/03/2018            45         269           cloud
35  01/04/2018            40         247           Rainy
36  02/04/2018            41         321           cloud
37  03/04/2018            32         321           cloud
38  04/04/2018            35         351           cloud
39  05/04/2018            22         302           cloud
40  06/04/2018            21         306  not available 
41  07/04/2018            23         385  not available 
42  08/04/2018            24         300  not available 
43  09/04/2018            35         213  not available 
44  10/04/2018            22         265  not available

In [63]:
gb = df.groupby("Event")

In [64]:
gb.head()

Day  Temperature   Wind Speed           Event
0   01/01/2018            35         320           Rainy
1   02/01/2018            28         123           cloud
2   03/01/2018            26         156             Hot
3   04/01/2018            29         174  not available 
4   05/01/2018            30         185           Rainy
5   06/01/2018            31         169           cloud
6   07/01/2018            32         245             Hot
7   08/01/2018            35         123  not available 
8   09/01/2018            40         156           cloud
9   10/01/2018            22         147             Hot
10  11/01/2018            35         563  not available 
11  12/01/2018            28         156           cloud
12  13/01/2018            24         412             Hot
13  14/01/2018            26         457           Rainy
14  01/02/2018            32         423           cloud
15  02/02/2018            35         156             Hot
16  03/02/2018            36         148  not available 
17  04/02/2018            37         175  not available 
18  05/02/2018            35         245           Rainy
23  10/02/2018            32         269           Rainy
31  07/03/2018            21         254             NaN

In [65]:
df.mean()["Wind Speed"]

258.44444444444446

In [66]:
gb.sum()

Temperature   Wind Speed
Event                                   
Hot                      301        2385
Rainy                    322        2738
cloud                    394        3134
not available            354        3119

In [67]:
gb.max()

Day  Temperature   Wind Speed
Event                                               
Hot             13/01/2018            43         412
Rainy           14/01/2018            41         457
cloud           12/01/2018            45         423
not available   11/01/2018            37         563

In [68]:
gb.min()

Day  Temperature   Wind Speed
Event                                               
Hot             02/02/2018            22         147
Rainy           01/01/2018            20         185
cloud           01/02/2018            22         123
not available   03/02/2018            21         123

In [ ]:
gb.describe()

Temperature                                                  \
                      count       mean       std   min    25%   50%    75%   
Event                                                                        
Hot                    10.0  30.100000  7.795298  22.0  24.25  28.0  34.25   
Rainy                  10.0  32.200000  6.214678  20.0  30.25  32.0  35.00   
cloud                  12.0  32.833333  6.780096  22.0  28.00  32.0  36.25   
not available          12.0  29.500000  5.977230  21.0  23.75  29.0  35.00   

                     Wind Speed                                                \
                 max      count        mean         std    min     25%    50%   
Event                                                                           
Hot             43.0       10.0  238.500000   77.495878  147.0  176.00  245.0   
Rainy           41.0       10.0  273.800000   72.286160  185.0  245.50  252.5   
cloud           45.0       12.0  261.166667   92.161748  123.0  165.75  277.0   
not available   37.0       12.0  259.916667  120.881203  123.0  174.75  233.5   

                               
                   75%    max  
Event                          
Hot             262.25  412.0  
Rainy           268.00  457.0  
cloud           321.00  423.0  
not available   301.50  563.0

## NP array Reading and Altering

In [ ]:
#importing numpy
import numpy as np


In [ ]:
#creating Random values
arr= np.arange(10)

In [ ]:
#printing out array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#checking With Where(condition,value to be overwrited,array_name)
out = np.where(arr%2==1,-1,arr)

In [ ]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
#initializing new blank list
List = []


In [ ]:
#getting the range
ran=int(input("enter the range = "))

In [ ]:
#appending values to the list
for i in range(ran):
    List.append(int(input("Enter the number = ")))

In [ ]:
#changing list to array
arr_1=np.array(List)

In [ ]:
#checking of intersection of two arrays
np.intersect1d(arr_1,arr)